import bcrypt from 'bcryptjs';

const data = {
  users:[
    {
      name: 'Riya',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
     // _id:'1',
      name: 'Dressberry red top',
      slug: 'dressberry-red-top',
      category: 'Women Westernwear',
      image: '/images/p1.jpg', // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'Dressberry',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality top',
    },
    {
      //_id:'2',
      name: 'Tokyo Talkies dress',
      slug: 'tokyo-talkies-dress',
      category: 'Women Westernwear',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 0,
      brand: 'Tokyo Talkies',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
     // _id:'3',
      name: 'Raymond Pant',
      slug: 'raymond-pant',
      category: 'Men Bottomwear',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
     // _id:'4',
      name: 'Turtle shirt',
      slug: 'turtle-shirt',
      category: 'Shirts',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Turtle',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id:'5',
       name: 'Dressberry black top',
       slug: 'dressberry-black-top',
       category: 'Women Westernwear',
       image: '/images/p5.jpg',
       price: 65,
       countInStock: 5,
       brand: 'Turtle',
       rating: 4.5,
       numReviews: 10,
       description: 'high quality product',
     },
     {
      // _id:'4',
       name: 'Roadster Tee',
       slug: 'roadster-tee',
       category: 'Tees',
       image: '/images/p6.jpg',
       price: 50,
       countInStock: 5,
       brand: 'Roadster',
       rating: 4.5,
       numReviews: 10,
       description: 'Cotton product',
     },
     {
      // _id:'4',
       name: 'Libas Kurti',
       slug: 'libas-kurti-women',
       category: 'Women Indianwear',
       image: '/images/p7.jpg',
       price: 125,
       countInStock: 5,
       brand: 'Libas',
       rating: 4.5,
       numReviews: 10,
       description: 'Rayon chikankari product',
     },
     {
      // _id:'4',
       name: 'Lee Cooper Jeans',
       slug: 'lee-jeans-men',
       category: 'Men Bottomwear',
       image: '/images/p8.jpg',
       price: 155,
       countInStock: 5,
       brand: 'Lee Cooper',
       rating: 4.5,
       numReviews: 10,
       description: 'Casual jeans denim',
     },
  ],
};
export default data;
