const data = {
    products: [
      {
        name: 'Dressberry red top',
        slug: 'dressberry-red-top',
        category: 'Tops',
        image: '/images/p1.jpg', // 679px × 829px
        price: 120,
        countInStock: 10,
        brand: 'Dressberry',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality top',
      },
      {
        name: 'Tokyo Talkies dress',
        slug: 'tokyo-talkies-dress',
        category: 'Dresses',
        image: '/images/p2.jpg',
        price: 250,
        countInStock: 20,
        brand: 'Tokyo Talkies',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        name: 'Raymond Pant',
        slug: 'raymond-pant',
        category: 'Pants',
        image: '/images/p3.jpg',
        price: 25,
        countInStock: 15,
        brand: 'Raymond',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        name: 'Turtle shirt',
        slug: 'turtle-shirt',
        category: 'Shirts',
        image: '/images/p4.jpg',
        price: 65,
        countInStock: 5,
        brand: 'Turtle',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
    ],
  };
  export default data;